# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
cache: packages


addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - tcl-dev
      - tk-dev
      - tk-table

r_binary_packages:
  - rgl


after_failure: "cat /home/travis/build/jfisher-usgs/RSurvey/RSurvey.Rcheck/00install.out"
